[phases.setup]
nixPkgs = ["python39", "python39Packages.pip"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'No build step needed for Python backend'"]

[start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
