[build]
builder = "nixpacks"

[deploy]
startCommand = ". venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.healthcheck]
path = "/"
timeout = 120

# Ignore frontend files during build
[build.ignore]
files = ["package.json", "package-lock.json", "vite.config.js", "src/", "public/", "index.html", "node_modules/", ".firebase/", "firebase.json", ".firebaserc", "dist/"]
